from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.display_text import normalize_display_text
from tools.validate_quotes import validate_document


def minute_to_index(minute: str) -> int:
    hour, minute_part = minute.split(":", 1)
    return int(hour) * 60 + int(minute_part)


def cpp_string(value: Any) -> str:
    if value is None:
        return "nullptr"

    escaped: list[str] = ['"']
    for char in normalize_display_text(value):
        codepoint = ord(char)
        if char == '"':
            escaped.append(r"\"")
        elif char == "\\":
            escaped.append(r"\\")
        elif char == "\n":
            escaped.append(r"\n")
        elif char == "\r":
            escaped.append(r"\r")
        elif char == "\t":
            escaped.append(r"\t")
        elif 0x20 <= codepoint <= 0x7E:
            escaped.append(char)
        elif codepoint <= 0xFFFF:
            escaped.append(f"\\u{codepoint:04x}")
        else:
            escaped.append(f"\\U{codepoint:08x}")
    escaped.append('"')
    return "".join(escaped)


def quote_rows(data: dict[str, Any]) -> list[tuple[int, dict[str, Any]]]:
    rows: list[tuple[int, dict[str, Any]]] = []
    for minute, entries in data["quotes"].items():
        minute_index = minute_to_index(minute)
        for quote in entries:
            rows.append((minute_index, quote))

    rows.sort(key=lambda row: (row[0], row[1]["id"]))
    return rows


def one_quote_per_minute(rows: list[tuple[int, dict[str, Any]]]) -> list[tuple[int, dict[str, Any]]]:
    selected: list[tuple[int, dict[str, Any]]] = []
    seen_minutes: set[int] = set()
    for minute_index, quote in rows:
        if minute_index in seen_minutes:
            continue
        selected.append((minute_index, quote))
        seen_minutes.add(minute_index)
    return selected


def generate_header(data: dict[str, Any], source_path: Path) -> str:
    rows = quote_rows(data)

    lines = [
        "// Generated by tools/generate_quotes_cpp.py.",
        f"// Source: {source_path.as_posix()}",
        "// Do not edit by hand.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "struct QuoteRecord {",
        "  uint16_t minute;",
        "  const char *id;",
        "  const char *text;",
        "  const char *time_text;",
        "  const char *title;",
        "  const char *author;",
        "};",
        "",
        f"static constexpr uint16_t kQuoteCount = {len(rows)};",
        "",
        "static const QuoteRecord kQuotes[] = {",
    ]

    for minute_index, quote in rows:
        lines.append(
            "  {"
            f"{minute_index}, "
            f"{cpp_string(quote['id'])}, "
            f"{cpp_string(quote['text'])}, "
            f"{cpp_string(quote['time_text'])}, "
            f"{cpp_string(quote['title'])}, "
            f"{cpp_string(quote['author'])}"
            "},"
        )

    lines.extend(
        [
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate firmware quote data from quote-library YAML.")
    parser.add_argument("input", type=Path, help="Quote-library YAML file")
    parser.add_argument("output", type=Path, help="Generated output path")
    parser.add_argument(
        "--format",
        choices=("cpp-header",),
        default="cpp-header",
        help="Output format. Default: cpp-header",
    )
    args = parser.parse_args()

    with args.input.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)

    validate_document(data, args.input)
    output = generate_header(data, args.input)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
